# Generated by Django 5.0.3 on 2024-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod_produto', models.IntegerField(primary_key=True, serialize=False)),
                ('ean_produto', models.BigIntegerField(default=0)),
                ('desc_produto', models.TextField(max_length=255)),
                ('linha_produto', models.TextField(max_length=255)),
                ('dt_val_produto', models.TextField(max_length=255)),
                ('lt_produto', models.TextField(max_length=255)),
            ],
        ),
    ]
