# Generated by Django 5.0.3 on 2024-03-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque_ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo_produto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dt_val_produto',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('prateleira', models.CharField(max_length=50)),
                ('caixa', models.CharField(max_length=50)),
                ('estoque_produto', models.IntegerField()),
                ('data_enderecamento', models.DateField()),
                ('cod_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_estoque_ecom.produto')),
            ],
        ),
    ]
